spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/todos
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true